# Generated by Django 5.2.6 on 2025-12-13 03:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "app_supplier",
            "0002_alter_purchaseorder_supplier_alter_purchaseorderitem_product",
        ),
        ("app_supplier", "0002_initial"),
    ]

    operations = []
