# Generated by Django 5.2.6 on 2025-12-13 03:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app_delivery", "0002_alter_delivery_sales_order"),
        ("app_delivery", "0003_initial"),
    ]

    operations = []
