# Generated by Django 5.2.6 on 2025-12-14 17:55

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("app_sales", "0009_salesorder_order_source"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="LumberingServiceOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("received_date", models.DateField(default=django.utils.timezone.now)),
                ("completed_date", models.DateField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "wood_type",
                    models.CharField(
                        help_text="Type of wood (Mahogany, Pine, etc.)", max_length=100
                    ),
                ),
                (
                    "quantity_logs",
                    models.IntegerField(
                        validators=[django.core.validators.MinValueValidator(1)]
                    ),
                ),
                (
                    "estimated_board_feet",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Initial estimate of board feet",
                        max_digits=10,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                    ),
                ),
                (
                    "service_fee_per_bf",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("5.00"),
                        help_text="Service fee per board foot",
                        max_digits=8,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                    ),
                ),
                (
                    "total_service_fee",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Calculated from actual output × fee per BF",
                        max_digits=12,
                        null=True,
                    ),
                ),
                (
                    "shavings_ownership",
                    models.CharField(
                        choices=[
                            ("customer", "Customer"),
                            ("lumber_company", "Lumber Company"),
                            ("shared", "Shared (50/50)"),
                        ],
                        default="lumber_company",
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="app_sales.customer",
                    ),
                ),
            ],
            options={
                "verbose_name": "Lumbering Service Order",
                "verbose_name_plural": "Lumbering Service Orders",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="LumberingServiceOutput",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "lumber_type",
                    models.CharField(
                        help_text="Type of lumber produced (2x4, 1x12, etc.)",
                        max_length=100,
                    ),
                ),
                (
                    "quantity_pieces",
                    models.IntegerField(
                        validators=[django.core.validators.MinValueValidator(1)]
                    ),
                ),
                (
                    "length_feet",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=8,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                    ),
                ),
                (
                    "width_inches",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=6,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                    ),
                ),
                (
                    "thickness_inches",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=6,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                    ),
                ),
                (
                    "board_feet",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                    ),
                ),
                (
                    "grade",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("select", "Select"),
                            ("common1", "Common #1"),
                            ("common2", "Common #2"),
                            ("common3", "Common #3"),
                        ],
                        default="common1",
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("recorded_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "service_order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="outputs",
                        to="app_lumbering_service.lumberingserviceorder",
                    ),
                ),
            ],
            options={
                "verbose_name": "Lumbering Service Output",
                "verbose_name_plural": "Lumbering Service Outputs",
                "ordering": ["-recorded_at"],
            },
        ),
        migrations.CreateModel(
            name="ShavingsRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                    ),
                ),
                (
                    "unit",
                    models.CharField(
                        choices=[
                            ("kg", "Kilograms"),
                            ("tons", "Tons"),
                            ("cubic_meters", "Cubic Meters"),
                            ("bags", "Bags"),
                        ],
                        default="kg",
                        max_length=20,
                    ),
                ),
                (
                    "customer_share",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        help_text="Customer's percentage share (0-100)",
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0")),
                            django.core.validators.MinValueValidator(Decimal("100")),
                        ],
                    ),
                ),
                (
                    "company_share",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        help_text="Company's percentage share (0-100)",
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0")),
                            django.core.validators.MinValueValidator(Decimal("100")),
                        ],
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("recorded_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "service_order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shavings",
                        to="app_lumbering_service.lumberingserviceorder",
                    ),
                ),
            ],
            options={
                "verbose_name": "Shavings Record",
                "verbose_name_plural": "Shavings Records",
                "ordering": ["-recorded_at"],
            },
        ),
    ]
