# Generated by Django 5.2.6 on 2025-12-14 12:26

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("app_supplier", "0003_merge_20251213_1143"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="WoodType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, unique=True)),
                (
                    "species",
                    models.CharField(
                        choices=[
                            ("hardwood", "Hardwood"),
                            ("softwood", "Softwood"),
                            ("tropical", "Tropical"),
                            ("mixed", "Mixed Species"),
                        ],
                        max_length=50,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                (
                    "default_diameter_inches",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Default log diameter in inches",
                        max_digits=5,
                        null=True,
                    ),
                ),
                (
                    "default_length_feet",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Default log length in feet",
                        max_digits=5,
                        null=True,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name_plural": "Wood Types",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="RoundWoodPurchaseOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("po_number", models.CharField(max_length=50, unique=True)),
                (
                    "po_number_supplier",
                    models.CharField(
                        blank=True,
                        help_text="Supplier's reference number for this order",
                        max_length=100,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("submitted", "Submitted"),
                            ("confirmed", "Confirmed"),
                            ("in_transit", "In Transit"),
                            ("delivered", "Delivered"),
                            ("inspected", "Inspected"),
                            ("stocked", "Stocked"),
                            ("cancelled", "Cancelled"),
                        ],
                        db_index=True,
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("order_date", models.DateField(default=django.utils.timezone.now)),
                ("expected_delivery_date", models.DateField()),
                ("actual_delivery_date", models.DateField(blank=True, null=True)),
                ("inspection_date", models.DateField(blank=True, null=True)),
                (
                    "total_volume_cubic_feet",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Total log volume in cubic feet",
                        max_digits=12,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "total_weight_tons",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Total weight in metric tons",
                        max_digits=12,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "unit_cost_per_cubic_foot",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "total_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=14,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "transaction_type",
                    models.CharField(
                        default="round_wood_goods_procurement",
                        help_text="Classified as: Round Wood Goods Procurement",
                        max_length=50,
                    ),
                ),
                (
                    "ownership_transfer_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Delivery"),
                            ("transferred", "Ownership Transferred"),
                            ("confirmed", "Confirmed in Stock"),
                        ],
                        default="pending",
                        help_text="Ownership transfers upon delivery and inspection",
                        max_length=20,
                    ),
                ),
                ("is_delivered", models.BooleanField(default=False)),
                (
                    "delivery_notes",
                    models.TextField(
                        blank=True, help_text="Notes about delivery condition"
                    ),
                ),
                (
                    "inspection_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Inspection"),
                            ("in_progress", "Inspection in Progress"),
                            ("passed", "Passed Inspection"),
                            ("failed", "Failed Inspection"),
                            ("partial", "Partially Accepted"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "inspection_notes",
                    models.TextField(
                        blank=True, help_text="Detailed inspection findings"
                    ),
                ),
                ("inspector_name", models.CharField(blank=True, max_length=200)),
                ("notes", models.TextField(blank=True)),
                (
                    "payment_terms",
                    models.CharField(
                        blank=True,
                        help_text="e.g., Net 30, COD, Advance Payment",
                        max_length=100,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="round_wood_orders_approved",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="round_wood_orders_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "supplier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="round_wood_orders",
                        to="app_supplier.supplier",
                    ),
                ),
            ],
            options={
                "verbose_name": "Round Wood Purchase Order",
                "verbose_name_plural": "Round Wood Purchase Orders",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="RoundWoodProcurementLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("created", "Order Created"),
                            ("submitted", "Order Submitted"),
                            ("confirmed", "Order Confirmed"),
                            ("delivered", "Delivered"),
                            ("inspection_started", "Inspection Started"),
                            ("inspection_passed", "Inspection Passed"),
                            ("inspection_failed", "Inspection Failed"),
                            ("stocked", "Stock In Completed"),
                            ("cancelled", "Order Cancelled"),
                            ("status_change", "Status Changed"),
                            ("note_added", "Note Added"),
                            ("item_updated", "Item Updated"),
                        ],
                        max_length=100,
                    ),
                ),
                ("old_value", models.TextField(blank=True)),
                ("new_value", models.TextField(blank=True)),
                ("details", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "performed_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="round_wood_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "purchase_order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="procurement_logs",
                        to="app_round_wood.roundwoodpurchaseorder",
                    ),
                ),
            ],
            options={
                "verbose_name": "Round Wood Procurement Log",
                "verbose_name_plural": "Round Wood Procurement Logs",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="RoundWoodStockTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[
                            ("stock_in", "Stock In (Purchase)"),
                            ("stock_out", "Stock Out (Usage/Sawing)"),
                            ("adjustment", "Inventory Adjustment"),
                            ("damage", "Damage Loss"),
                            ("waste", "Waste/Scrap"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "quantity_logs",
                    models.IntegerField(
                        validators=[django.core.validators.MinValueValidator(1)]
                    ),
                ),
                (
                    "volume_cubic_feet",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "cost_per_cubic_foot",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "total_cost",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=14,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "reference_type",
                    models.CharField(
                        choices=[
                            ("purchase_order", "Purchase Order"),
                            ("sales_order", "Sales Order"),
                            ("production", "Production/Sawing"),
                            ("adjustment", "Manual Adjustment"),
                            ("other", "Other"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "reference_id",
                    models.CharField(
                        blank=True,
                        help_text="PO number, SO number, or other reference",
                        max_length=100,
                    ),
                ),
                (
                    "reason",
                    models.CharField(
                        blank=True,
                        help_text="Reason for stock out or adjustment",
                        max_length=200,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="round_wood_transactions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "wood_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stock_transactions",
                        to="app_round_wood.woodtype",
                    ),
                ),
            ],
            options={
                "verbose_name": "Round Wood Stock Transaction",
                "verbose_name_plural": "Round Wood Stock Transactions",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="RoundWoodPurchaseOrderItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantity_logs",
                    models.IntegerField(
                        help_text="Number of logs in this batch",
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                (
                    "diameter_inches",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Average log diameter in inches",
                        max_digits=5,
                    ),
                ),
                (
                    "length_feet",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Average log length in feet",
                        max_digits=5,
                    ),
                ),
                (
                    "volume_cubic_feet",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Total volume calculated from logs",
                        max_digits=12,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "unit_cost_per_cubic_foot",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "subtotal",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=14,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "quality_grade",
                    models.CharField(
                        choices=[
                            ("premium", "Premium Grade"),
                            ("standard", "Standard Grade"),
                            ("utility", "Utility Grade"),
                            ("industrial", "Industrial Grade"),
                        ],
                        default="standard",
                        max_length=50,
                    ),
                ),
                (
                    "inspection_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Inspection"),
                            ("in_progress", "Inspection in Progress"),
                            ("passed", "Passed Inspection"),
                            ("failed", "Failed Inspection"),
                            ("partial", "Partially Accepted"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("inspection_notes", models.TextField(blank=True)),
                (
                    "quantity_accepted",
                    models.IntegerField(
                        blank=True,
                        help_text="Number of logs accepted after inspection",
                        null=True,
                    ),
                ),
                (
                    "quantity_rejected",
                    models.IntegerField(
                        default=0, help_text="Number of logs rejected during inspection"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "purchase_order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="app_round_wood.roundwoodpurchaseorder",
                    ),
                ),
                (
                    "wood_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="purchase_items",
                        to="app_round_wood.woodtype",
                    ),
                ),
            ],
            options={
                "verbose_name": "Round Wood Purchase Order Item",
                "verbose_name_plural": "Round Wood Purchase Order Items",
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="RoundWoodInventory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "total_logs_in_stock",
                    models.IntegerField(
                        default=0,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "total_cubic_feet_in_stock",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "total_cost_invested",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Total cost of all stocked round wood",
                        max_digits=14,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "average_cost_per_cubic_foot",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "warehouse_location",
                    models.CharField(
                        blank=True,
                        help_text="e.g., Yard A, Section B, Stack 3",
                        max_length=200,
                    ),
                ),
                ("last_updated", models.DateTimeField(auto_now=True)),
                ("last_stock_in_date", models.DateField(blank=True, null=True)),
                (
                    "wood_type",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="round_wood_inventory",
                        to="app_round_wood.woodtype",
                    ),
                ),
            ],
            options={
                "verbose_name": "Round Wood Inventory",
                "verbose_name_plural": "Round Wood Inventories",
            },
        ),
        migrations.AddIndex(
            model_name="roundwoodpurchaseorder",
            index=models.Index(
                fields=["po_number"], name="app_round_w_po_numb_96f51e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="roundwoodpurchaseorder",
            index=models.Index(
                fields=["status", "-created_at"], name="app_round_w_status_cdb314_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="roundwoodpurchaseorder",
            index=models.Index(
                fields=["supplier", "-created_at"],
                name="app_round_w_supplie_5c18f1_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="roundwoodstocktransaction",
            index=models.Index(
                fields=["wood_type", "-created_at"],
                name="app_round_w_wood_ty_05b839_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="roundwoodstocktransaction",
            index=models.Index(
                fields=["transaction_type", "-created_at"],
                name="app_round_w_transac_7cfcf8_idx",
            ),
        ),
    ]
