# Generated by Django 5.2.6 on 2025-12-14 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_round_wood", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="roundwoodpurchaseorder",
            name="payment_terms",
            field=models.CharField(
                default="Cash on Delivery (COD)",
                help_text="e.g., Net 30, COD, Advance Payment",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="roundwoodpurchaseorder",
            name="po_number",
            field=models.CharField(
                blank=True,
                help_text="Auto-generated PO number",
                max_length=50,
                unique=True,
            ),
        ),
    ]
