# Generated by Django 5.2.6 on 2025-12-14 13:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_round_wood", "0002_alter_roundwoodpurchaseorder_payment_terms_and_more"),
        ("app_supplier", "0003_merge_20251213_1143"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="roundwoodprocurementlog",
            name="performed_by",
        ),
        migrations.RemoveField(
            model_name="roundwoodprocurementlog",
            name="purchase_order",
        ),
        migrations.RemoveField(
            model_name="roundwoodstocktransaction",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="roundwoodstocktransaction",
            name="wood_type",
        ),
        migrations.RemoveField(
            model_name="roundwoodpurchaseorder",
            name="actual_delivery_date",
        ),
        migrations.RemoveField(
            model_name="roundwoodpurchaseorder",
            name="approved_by",
        ),
        migrations.RemoveField(
            model_name="roundwoodpurchaseorder",
            name="delivery_notes",
        ),
        migrations.RemoveField(
            model_name="roundwoodpurchaseorder",
            name="expected_delivery_date",
        ),
        migrations.RemoveField(
            model_name="roundwoodpurchaseorder",
            name="inspection_date",
        ),
        migrations.RemoveField(
            model_name="roundwoodpurchaseorder",
            name="inspection_notes",
        ),
        migrations.RemoveField(
            model_name="roundwoodpurchaseorder",
            name="inspection_status",
        ),
        migrations.RemoveField(
            model_name="roundwoodpurchaseorder",
            name="inspector_name",
        ),
        migrations.RemoveField(
            model_name="roundwoodpurchaseorder",
            name="is_delivered",
        ),
        migrations.RemoveField(
            model_name="roundwoodpurchaseorder",
            name="ownership_transfer_status",
        ),
        migrations.RemoveField(
            model_name="roundwoodpurchaseorder",
            name="payment_terms",
        ),
        migrations.RemoveField(
            model_name="roundwoodpurchaseorder",
            name="total_weight_tons",
        ),
        migrations.RemoveField(
            model_name="roundwoodpurchaseorder",
            name="transaction_type",
        ),
        migrations.RemoveField(
            model_name="roundwoodpurchaseorderitem",
            name="inspection_notes",
        ),
        migrations.RemoveField(
            model_name="roundwoodpurchaseorderitem",
            name="inspection_status",
        ),
        migrations.RemoveField(
            model_name="roundwoodpurchaseorderitem",
            name="quality_grade",
        ),
        migrations.RemoveField(
            model_name="roundwoodpurchaseorderitem",
            name="quantity_accepted",
        ),
        migrations.RemoveField(
            model_name="roundwoodpurchaseorderitem",
            name="quantity_rejected",
        ),
        migrations.AddField(
            model_name="roundwoodpurchaseorder",
            name="delivery_date",
            field=models.DateField(
                blank=True, help_text="Actual delivery date", null=True
            ),
        ),
        migrations.AddField(
            model_name="roundwoodpurchaseorder",
            name="payment_status",
            field=models.CharField(
                choices=[("unpaid", "Unpaid"), ("paid", "Paid")],
                default="unpaid",
                help_text="Track if supplier has been paid",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="roundwoodpurchaseorder",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("ordered", "Ordered"),
                    ("delivered", "Delivered"),
                    ("cancelled", "Cancelled"),
                ],
                db_index=True,
                default="draft",
                max_length=20,
            ),
        ),
        migrations.AddIndex(
            model_name="roundwoodpurchaseorder",
            index=models.Index(
                fields=["payment_status", "-created_at"],
                name="app_round_w_payment_8397c2_idx",
            ),
        ),
        migrations.DeleteModel(
            name="RoundWoodProcurementLog",
        ),
        migrations.DeleteModel(
            name="RoundWoodStockTransaction",
        ),
    ]
