# Generated by Django 5.2.6 on 2025-12-14 17:08

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_round_wood", "0003_remove_roundwoodprocurementlog_performed_by_and_more"),
        ("app_supplier", "0003_merge_20251213_1143"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="roundwoodpurchaseorderitem",
            name="purchase_order",
        ),
        migrations.RemoveField(
            model_name="roundwoodpurchaseorderitem",
            name="wood_type",
        ),
        migrations.CreateModel(
            name="RoundWoodPurchase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantity_logs",
                    models.IntegerField(
                        help_text="Number of logs purchased",
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                (
                    "diameter_inches",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Average log diameter in inches",
                        max_digits=5,
                    ),
                ),
                (
                    "length_feet",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Average log length in feet",
                        max_digits=5,
                    ),
                ),
                (
                    "volume_cubic_feet",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Total volume in cubic feet",
                        max_digits=12,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "unit_cost_per_cubic_foot",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Cost per cubic foot",
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "total_cost",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Total purchase cost",
                        max_digits=14,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("purchase_date", models.DateField(default=django.utils.timezone.now)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="round_wood_purchases_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "supplier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="round_wood_purchases",
                        to="app_supplier.supplier",
                    ),
                ),
                (
                    "wood_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="purchases",
                        to="app_round_wood.woodtype",
                    ),
                ),
            ],
            options={
                "verbose_name": "Round Wood Purchase",
                "verbose_name_plural": "Round Wood Purchases",
                "ordering": ["-purchase_date", "-created_at"],
            },
        ),
        migrations.DeleteModel(
            name="RoundWoodPurchaseOrder",
        ),
        migrations.DeleteModel(
            name="RoundWoodPurchaseOrderItem",
        ),
        migrations.AddIndex(
            model_name="roundwoodpurchase",
            index=models.Index(
                fields=["supplier", "-purchase_date"],
                name="app_round_w_supplie_dc3f39_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="roundwoodpurchase",
            index=models.Index(
                fields=["status", "-purchase_date"],
                name="app_round_w_status_7c0baa_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="roundwoodpurchase",
            index=models.Index(
                fields=["wood_type", "-purchase_date"],
                name="app_round_w_wood_ty_3e2ada_idx",
            ),
        ),
    ]
