# Generated by Django 5.2.4 on 2025-12-13 04:19

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app_sales", "0007_notification_models"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="orderconfirmation",
            new_name="app_sales_o_custome_3a26cb_idx",
            old_name="app_sales_oc_custome_idx",
        ),
        migrations.RenameIndex(
            model_name="orderconfirmation",
            new_name="app_sales_o_status_103e2c_idx",
            old_name="app_sales_oc_status_idx",
        ),
        migrations.RenameIndex(
            model_name="ordernotification",
            new_name="app_sales_o_custome_1b143f_idx",
            old_name="app_sales_o_custome_idx",
        ),
        migrations.RenameIndex(
            model_name="ordernotification",
            new_name="app_sales_o_is_read_73a19b_idx",
            old_name="app_sales_o_is_read_idx",
        ),
        migrations.RenameIndex(
            model_name="ordernotification",
            new_name="app_sales_o_notific_d8ad21_idx",
            old_name="app_sales_o_notif_type_idx",
        ),
    ]
