# Generated by Django 5.2.6 on 2025-12-11 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_inventory", "0004_alter_lumbercategory_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="lumberproduct",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="products/"),
        ),
    ]
